name: Ooredoo Proxy Scraper & Checker

on:
  workflow_dispatch: # يعمل فقط عندما يطلبه بوت تيليجرام أو تضغطه يدوياً

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # صلاحية الكتابة لتحديث الملف في المستودع تلقائياً
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install requests

      - name: Run Scraper and Send to Telegram
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GH_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: python check_and_send.py
